main: fr.liveweeeb.Nocila
version: 1.4.0-BETA-1
name: Nocila
description: Nocila is a plugin designed to simplify vanilla commands.
author: liveweeeb
api-version: 1.13

commands:
  about:
    description: About Nocila
    usage: /about
  broadcast:
    description: Send a message to all players
    usage: /broadcast <message>
    permission: nocila.broadcast
    permission-message: "§cYou don't have permission to use this command!"
  day:
    description: Set the day
    usage: /day
    permission: nocila.day
    permission-message: "§cYou don't have permission to use this command!"
  night:
    description: Set the night
    usage: /night
    permission: nocila.night
    permission-message: "§cYou don't have permission to use this command!"
  repair:
    description: Repair the item in your hand
    usage: /repair
    permission: nocila.repair
    permission-message: "§cYou don't have permission to use this command!"
  rename:
    description: Rename the item in your hand
    usage: /rename <name>
    permission: nocila.rename
    permission-message: "§cYou don't have permission to use this command!"
  lore:
    description: Add lore to the item in your hand
    usage: /lore <text>
    permission: nocila.lore
    permission-message: "§cYou don't have permission to use this command!"
  smite:
    description: Strike a player with lightning
    usage: /smite <player>
    permission: nocila.smite
    permission-message: "§cYou don't have permission to use this command!"
  craft:
    description: Open a Workbench
    usage: /craft
    permission: nocila.craft
    permission-message: "§cYou don't have permission to use this command!"
  hat:
    description: Wear the item in your hand as a hat
    usage: /hat
    permission: nocila.hat
    permission-message: "§cYou don't have permission to use this command!"
  nocila:
    description: Show nocila command list
    usage: /nocila <help|debug|reload>
    permission: nocila.nocila
    permission-message: "§cYou don't have permission to use this command!"
  delfire:
    description: Remove fire around you
    usage: /delfire
    permission: nocila.delfire
    permission-message: "§cYou don't have permission to use this command!"
  masssummon:
    description: Spawn the number of entities requested
    usage: /masssummon <entity> <numer>
    permission: nocila.masssummon
    permission-message: "§cYou don't have permission to use this command!"
