main: fr.liveweeeb.Nocila
version: 1.0.0-BETA
name: Nocila
description: Nocila est un plugin qui vise a simplifier les commandes vanilla
author: liveweeeb
api-version: 1.13

commands:
  about:
    description: A propos de Nocila
    usage: /about
  broadcast:
    description: Envoie un message a tous les joueurs
    usage: /broadcast <message>